#!/usr/bin/env bash
#
# Regenerate the script by running:
# docker run --rm -v "$(pwd):/work" -u "$(id -u):$(id -g)" matejak/argbash -o assemble-pkgs.sh resources/assemble-pkgs.argbash
#
# ARG_OPTIONAL_REPEATED([input],[i],[List of input libraries])
# ARG_OPTIONAL_SINGLE([output-dir],[o],[Output directory])
# ARG_OPTIONAL_SINGLE([artifact-dir],[],[If this is set, artifacts are picked from this directory instead of being downloaded from a github release])
# ARG_OPTIONAL_SINGLE([release],[],[Select the github release from which to download artifacts])

# ARG_HELP([Fetch and combine multiple packages from build-scripts into one directory])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='ioh'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_input=()
_arg_output_dir=
_arg_artifact_dir=
_arg_release=


print_help()
{
	printf '%s\n' "Fetch and combine multiple packages from build-scripts into one directory"
	printf 'Usage: %s [-i|--input <arg>] [-o|--output-dir <arg>] [--artifact-dir <arg>] [--release <arg>] [-h|--help]\n' "$0"
	printf '\t%s\n' "-i, --input: List of input libraries (empty by default)"
	printf '\t%s\n' "-o, --output-dir: Output directory (no default)"
	printf '\t%s\n' "--artifact-dir: If this is set, artifacts are picked from this directory instead of being downloaded from a github release (no default)"
	printf '\t%s\n' "--release: Select the github release from which to download artifacts (no default)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	local _key
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-i|--input)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_input+=("$2")
				shift
				;;
			--input=*)
				_arg_input+=("${_key##--input=}")
				;;
			-i*)
				_arg_input+=("${_key##-i}")
				;;
			-o|--output-dir)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_output_dir="$2"
				shift
				;;
			--output-dir=*)
				_arg_output_dir="${_key##--output-dir=}"
				;;
			-o*)
				_arg_output_dir="${_key##-o}"
				;;
			--artifact-dir)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_artifact_dir="$2"
				shift
				;;
			--artifact-dir=*)
				_arg_artifact_dir="${_key##--artifact-dir=}"
				;;
			--release)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_release="$2"
				shift
				;;
			--release=*)
				_arg_release="${_key##--release=}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


set -e

function check_command {
    if ! command -v "$1" &> /dev/null ; then
        echo "Missing dependency: $1" >&2
        exit 1
    fi
}

check_command curl
check_command mktemp
check_command xz
check_command tar

VERSION=v0.1.0
if test -n "$_arg_release" ; then
    VERSION="$_arg_release"
fi

if test -z "$_arg_output_dir" ; then
    echo "No output directory set" >&2
    exit 1
fi

ASSEMBLED_DIR="$(realpath "$_arg_output_dir")"
if test -e "$ASSEMBLED_DIR" ; then
    echo "Output directory $ASSEMBLED_DIR already exists. aborting." >&2
    exit 1
fi

ARTIFACT_DIR=""
if test -n "$_arg_artifact_dir" ; then
    ARTIFACT_DIR="$(realpath "$_arg_artifact_dir")"
    if ! test -d "$ARTIFACT_DIR" ; then
        echo "Artifact directory $ARTIFACT_DIR does not exist" >&2
        exit 1
    fi
fi

TMP_DIR=$(mktemp -d)

for input in "${_arg_input[@]}" ; do
    output="$TMP_DIR/$input.tar.xz"
    if test -f "$output" ; then
        echo "Temporary file $output already exists. aborting." >&2
        exit 1
    fi
    if test -n "$ARTIFACT_DIR" ; then
        cp "$ARTIFACT_DIR/$input.tar.xz" "$output"
    else
        curl -sSfL "https://github.com/wasix-org/build-scripts/releases/download/$VERSION/$input.tar.xz" -o "$output"
    fi
done

mkdir -p "$ASSEMBLED_DIR"

for input in "${_arg_input[@]}" ; do
    tar mxJf "$TMP_DIR/$input.tar.xz" -C "$ASSEMBLED_DIR"
done

# ] <-- needed because of Argbash
