[package]
name = "wasmer/python-native"
version = "0.1.0"
entrypoint = "python"

[fs]
"/usr/local/ssl" = "../../python-wasix-binaries/ssl-certs"
"/usr/local/lib" = "../../pkgs/cpython.sysroot/usr/local/lib/wasm32-wasi"
"/usr/terminfo" = "../../pkgs/cpython.sysroot/usr/local/lib/terminfo"
"/cpython" = "../../pkgs/cpython.lib/usr/local"

[[module]]
name = "python"
source = "../../pkgs/cpython.lib/usr/local/bin/python3.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "python"
module = "python"
runner = "wasi"

[command.annotations.wasi]
env = [
    "PYTHONEXECUTABLE=/bin/python",
    "PYTHONHOME=/cpython",
    "TERMINFO_DIRS=/usr/terminfo",
    # pyrepl is currently not working 100% correctly, so disable it for now.
    # pyrepl will be disabled when TERM=dumb. Set to xterm, once wasmer supports all the required features.
    "TERM=dumb",
]
