[package]
name = "python/python"
version = "0.1.0"
entrypoint = "python"

[fs]
# Mounting root to / prevents users from mounting anything else.
# So we mount /usr/local and /lib explicitly.
"/lib" = "./root/lib"
"/usr/local" = "./root/usr/local"

[[module]]
name = "python"
source = "./root/usr/local/bin/python3.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "python"
module = "python"
runner = "wasi"

[command.annotations.wasi]
env = [
    "PYTHONEXECUTABLE=/bin/python",
    # "PYTHONHOME=/usr/local",
    # pyrepl is currently not working 100% correctly, so disable it for now.
    # pyrepl will be disabled when TERM=dumb. Set to xterm, once wasmer supports all the required features.
    "TERM=dumb",
]
